# Generated by Django 2.2.16 on 2022-08-03 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220801_2346'),
        ('users', '0002_auto_20220730_0923'),
    ]

    operations = [
    ]
